name: cppcheck
on: [push, pull_request]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: tonybaloney/cppcheck-action@master
        with:
          path: 'src'
