name: cppcheck
on: [push, pull_request]
jobs:
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install cppcheck
      run: sudo apt-get install cppcheck

    - name: Run cppcheck
      run: cppcheck --version && cppcheck src/
